# Generated by Django 4.0.6 on 2022-08-07 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=2000, null='False')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user_following', to=settings.AUTH_USER_MODEL)),
                ('user_post', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='liked_on', to='network.post')),
                ('user_like', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='commented_on', to='network.post')),
                ('user_comment', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user_comm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
