# Generated by Django 4.0.6 on 2022-08-16 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
