# Generated by Django 4.0.6 on 2022-08-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
